"""프롬프트 모듈"""
from .supervisor_prompt import SUPERVISOR_SYSTEM_PROMPT, SUPERVISOR_USER_PROMPT_TEMPLATE
from .web_search_prompt import WEB_SEARCH_SYSTEM_PROMPT, WEB_SEARCH_USER_PROMPT_TEMPLATE
from .rag_prompt import RAG_SYSTEM_PROMPT, RAG_USER_PROMPT_TEMPLATE

__all__ = [
    "SUPERVISOR_SYSTEM_PROMPT",
    "SUPERVISOR_USER_PROMPT_TEMPLATE",
    "WEB_SEARCH_SYSTEM_PROMPT",
    "WEB_SEARCH_USER_PROMPT_TEMPLATE",
    "RAG_SYSTEM_PROMPT",
    "RAG_USER_PROMPT_TEMPLATE"
]

